meta_product_name: "Impactasso"
meta_title: "Impactasso - Agis facilement pour des causes qui te tiennent à coeur"
meta_description: "La solution pour trouver facilement des associations et des missions de bénévolat qui te ressemblent, autour de chez toi!"
meta_image: "logo.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
