meta_product_name: "Impactasso"
meta_title: "Impactasso - Product tagline"
meta_description: "Une appli qui permet d'agir facilement pour des causes qui te tiennent à coeur, elle te permet de trouver des associations proches des tes convictions autour de chez toi"
meta_image: "logo.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
